name: Deploy Bicep file
on:
  push:
    branches: [ main ]

permissions: 
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Azure CLI script
      uses: azure/login@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./storageAccount.bicep
        parameters: 'storagePrefix=mystorageaccountdlv storageSKU=Standard_LRS'
        failOnStdErr: false
