name: Deploy Bicep file

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log into Azure using federated identity with OIDC and allow-no-subscriptions
    - name: Log into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Make sure this is correct
        allow-no-subscriptions: true  # If no subscription is assigned to the service principal

    # Optional: Check Azure CLI login (Shows the active account)
    - name: Check Azure Account
      run: az account show

    # Deploy Bicep template using ARM Deploy action
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Ensure this matches the login
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./storageAccount.bicep  # Path to your Bicep file
        parameters: 'storagePrefix=mystorageaccountdlv storageSKU=Standard_LRS'
        failOnStdErr: false
